name: jose
description: Javascript Object Signing and Encryption (JOSE) library supporting JWE, JWS, JWK and JWT
version: 0.3.4
homepage: https://github.com/appsup-dart/jose
funding:
 - https://github.com/sponsors/rbellens


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto_keys: ^0.3.0+1
  meta: ^1.1.6
  typed_data: ^1.0.0
  x509: ^0.2.1
  http: ^1.0.0
  http_parser: ^4.0.0
  asn1lib: ^1.0.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0

false_secrets:
  - test/pem/*
  - example/*.key